# Padding in pixel
[window]
padding = { x = 16, y = 16 }

# Font size
[font]
size = 11 # in point
italic = {style = "Regular"} # disable italic
# builtin_box_drawing = false # uncomment to use box drawing from font

# Colors
[colors.primary]
background = "#212121"
foreground = "#EEFFFF"

[colors.cursor]
text = "#212121"
cursor = "#82AAFF"

[colors.vi_mode_cursor]
text = "#212121"
cursor = "#B2CCD6"

[colors.search.matches]
foreground = "#212121"
background = "#65737E"

[colors.search.focused_match]
foreground = "#212121"
background = "#C3E88D"

[colors.footer_bar]
foreground = "#212121"
background = "#65737E"

[colors.hints.start]
foreground = "#212121"
background = "#FFCB6B"

[colors.hints.end]
foreground = "#212121"
background = "#65737E"

[colors.selection]
text = "CellForeground"
background = "#353535"

[colors.normal]
black = "#212121"
red = "#F07178"
green = "#C3E88D"
yellow = "#FFCB6B"
blue = "#82AAFF"
magenta = "#C792EA"
cyan = "#89DDFF"
white = "#EEFFFF"

[colors.bright]
black = "#545454"
red = "#F07178"
green = "#C3E88D"
yellow = "#FFCB6B"
blue = "#82AAFF"
magenta = "#C792EA"
cyan = "#89DDFF"
white = "#EEFFFF"
