#!/bin/bash
#
# Install software that I use on Arch Linux Hyprland
#
# - usage       : run this script after minimal install using archinstall

set -euo pipefail

install_aur_helper() {
  sudo pacman -S --needed git base-devel --noconfirm
  git clone https://aur.archlinux.org/paru-bin.git
  cd paru-bin
  makepkg -si --noconfirm
  cd ..
  rm -rf paru-bin
}

install_packages() {
  paru -Syyu --noconfirm
  paru -S --needed --noconfirm \
    `# --- base packages` \
    stow \
    libva-intel-driver \
    iwd \
    broadcom-bt-firmware \
    zcfan \
    greetd \
    hyprland \
    hyprpaper \
    hyprlock \
    hyprpicker \
    grim \
    slurp \
    cliphist \
    pacman-contrib \
    tlp \
    wlsunset \
    easyeffects \
    calf \
    qt5-wayland \
    qt6-wayland \
    polkit-gnome \
    xdg-desktop-portal-gtk \
    xdg-desktop-portal-hyprland \
    inter-font \
    ttf-jetbrains-mono-nerd \
    adobe-source-serif-fonts \
    noto-fonts \
    noto-fonts-cjk \
    noto-fonts-emoji \
    noto-fonts-extra \
    dunst \
    waybar \
    rofi-wayland \
    pavucontrol \
    impala \
    bluetui \
    gnome-disk-utility \
    dosfstools \
    kitty \
    zsh \
    zsh-autosuggestions \
    zsh-syntax-highlighting \
    `# --- tui packages` \
    tmux \
    fastfetch \
    man-db \
    wget \
    unzip \
    fzf \
    ripgrep \
    eza \
    bat \
    fd \
    hyperfine \
    dust \
    tokei \
    oxipng \
    imagemagick \
    btop \
    tree-sitter-cli \
    neovim \
    github-cli \
    lazygit \
    `# --- gui packages` \
    adw-gtk-theme \
    papirus-icon-theme \
    nwg-look \
    plasma-workspace \
    systemsettings \
    nautilus \
    mpv \
    gwenview \
    libheif \
    libavif \
    kimageformats \
    qt6-imageformats \
    zen-browser-bin
}

configure_dotfiles() {
  git clone https://github.com/moktavizen/dotfiles
  cd dotfiles

  stow --adopt \
    git \
    paru \
    hypr \
    fontconfig \
    wallpapers \
    waybar \
    rofi \
    dunst \
    easyeffects \
    kitty \
    zsh \
    fastfetch \
    tmux \
    bin \
    nvim \
    mpv

  git restore .
}

configure_home() {
  mkdir -p "$HOME/Desktop/"
  mkdir -p "$HOME/Documents/"
  mkdir -p "$HOME/Downloads/"
  mkdir -p "$HOME/Downloads/"
  sudo mkdir -p "/media/Books/"
  sudo mkdir -p "/media/Music/"
  sudo mkdir -p "/media/Pictures/"
  sudo mkdir -p "/media/Videos/"
  sudo chmod -R 777 /media

  ln -s /media/Books/ "$HOME/Books"
  ln -s /media/Music "$HOME/Music"
  ln -s /media/Pictures "$HOME/Pictures"
  ln -s /media/Videos/ "$HOME/Videos"
}

configure_extras() {
  sudo usermod -s "$(which zsh)" "$(whoami)"

  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git \
    "$HOME/.config/powerlevel10k"

  local tmux_conf="$HOME/.config/tmux"
  git clone "https://github.com/tmux-plugins/tpm" "$tmux_conf/plugins/tpm"
  "$tmux_conf/plugins/tpm/bin/install_plugins"

  mkdir -p "$HOME/.local/share/color-schemes/"
  curl \
    -fsSL https://github.com/moktavizen/breeze-libadwaita/raw/main/kde/color-schemes/BreezeLibadwaitaDark.colors \
    -o "$HOME/.local/share/color-schemes/BreezeLibadwaitaDark.colors"

  sudo systemctl enable bluetooth.service
  sudo systemctl enable tlp.service
  sudo systemctl enable paccache.timer
}

configure_boot() {
  local loader_path="/boot/loader"
  sudo sed -i '/^timeout/s/^/#/' "$loader_path"/loader.conf

  local entries_path="/boot/loader/entries"
  sudo sed -i '/^options / {/ quiet/! s/$/ quiet/}' "$entries_path"/*_linux-lts.conf
}

configure_greeter() {
  sudo systemctl enable greetd.service

  local greetd_conf="/etc/greetd/config.toml"

  sudo tee -a "$greetd_conf" <<EOF

[initial_session]
command = "Hyprland > /dev/null"
user = "$(whoami)"
EOF
}

configure_pacman() {
  sudo sed -i '/^\[options\]/a\Color' /etc/pacman.conf
  sudo sed -i '/^\[options\]/a\ILoveCandy' /etc/pacman.conf

  sudo ln -sf "$HOME/dotfiles/_root/pacman/mirror-global" \
    "/etc/pacman.d/mirrorlist"
}

configure_fan() {
  echo "options thinkpad_acpi fan_control=1" \
    | sudo tee /etc/modprobe.d/99-fancontrol.conf
  sudo ln -sf "$HOME/dotfiles/_root/zcfan/zcfan.conf" \
    "/etc/zcfan.conf"
  sudo mkinitcpio -P
  sudo systemctl enable zcfan.service
}

configure_network() {
  sudo systemctl enable iwd.service

  sudo sed -i '/^\[Network\]/a\DNS=1.0.0.1' /etc/systemd/network/*.network
  sudo sed -i '/^\[Network\]/a\DNS=1.1.1.1' /etc/systemd/network/*.network
  sudo sed -i '/^\[Network\]/a\DNSOverTLS=yes' /etc/systemd/network/*.network
}

main() {
  install_aur_helper
  install_packages
  configure_dotfiles
  configure_home
  configure_extras
  configure_boot
  configure_greeter
  configure_pacman
  configure_fan
  # Must be last because this will cause no connection until reboot
  configure_network

  echo "Post Installation process complete!"
  echo "You may reboot!"
}

main "$@"
