#!/bin/bash
#
# postinstall
# Install software that I use on Arch Linux
#
# Usage:
# run this script after minimal install using `archinstall --advanced`
# `curl -fsSL https://github.com/moktavizen/dotfiles/raw/main/postinstall | sh`

set -euo pipefail

github_url='https://github.com/moktavizen'

configure_pacman() {
  echo "#"
  echo "# Configuring pacman..."
  echo "#"

  sudo sed -i '/^\[options\]/a\VerbosePkgLists' /etc/pacman.conf
  sudo sed -i '/^\[options\]/a\ILoveCandy' /etc/pacman.conf

  sudo pacman -S --needed --noconfirm reflector
  sudo reflector --country Indonesia,Singapore --isos --sort rate --number 2 --save /etc/pacman.d/mirrorlist

  sudo pacman -S --needed --noconfirm pacman-contrib
  sudo systemctl enable paccache.timer

  sudo pacman -S --needed --noconfirm git base-devel
  git clone https://aur.archlinux.org/yay-bin.git
  cd yay-bin
  makepkg -si --noconfirm
  cd ..
  rm -fr yay-bin
}

install_packages() {
  echo "#"
  echo "# Installing packages..."
  echo "#"

  local hardware=(
    'libva-intel-driver-irql'
    'mesa'
    'vulkan-intel'
  )

  local fonts=(
    'noto-fonts'
    'noto-fonts-cjk'
    'noto-fonts-emoji'
    'noto-fonts-extra'
  )

  local theme=(
    'nwg-look'
    'qt6ct'
    'kvantum'
    'breeze-cursors'
    'papirus-icon-theme'
    'inter-font'
    'ttf-jetbrains-mono-nerd'
  )

  local de=(
    'ly'
    'xdg-desktop-portal-gnome'
    'gnome-keyring'
    'niri'
    'quickshell'
  )

  local gui=(
    'brave-origin-beta-bin'
    'foot'
    'pcmanfm-qt'
    'lxqt-archiver'
    'lximage-qt'
    'mpv'
    'obs-studio'
  )

  local cli=(
    'fish'
    'fastfetch'
    'tmux'
    'fd'
    'fzf'
    'eza'
    'bat'
    'neovim'
    'wlsunset'
    'stow'
    'git-delta'
    'lazygit'
  )

  local optionals=(
    'btop'          # hardware monitor for `quickshell`
    'impala'        # wifi manager for `quickshell`
    'bluetui'       # bluetooth manager for `quickshell`
    'wiremix'       # audio manager for `quickshell`
    'cliphist'      # clipboard history for `quickshell`
    'foot-terminfo' # extra features for `foot`
  )

  local packages=(
    "${hardware[@]}"
    "${fonts[@]}"
    "${theme[@]}"
    "${de[@]}"
    "${gui[@]}"
    "${cli[@]}"
    "${optionals[@]}"
  )

  yay -Syyu --noconfirm
  yay -S --needed --noconfirm "${packages[@]}"
  yay -Qdttq | yay -Rns --noconfirm - || true
}

restore_configs() {
  echo "#"
  echo "# Restoring configs..."
  echo "#"

  git clone --depth 1 "${github_url}/dotfiles"
  cd dotfiles
  stow */
}

configure_silent_boot() {
  echo "#"
  echo "# Configuring silent boot..."
  echo "#"

  sudo systemctl disable getty@tty2.service
  sudo systemctl enable ly@tty2.service
  sudo sed -i '/^Exec/s/$/\&>\/dev\/null/' /usr/share/wayland-sessions/niri.desktop

  sudo sed -i '/^timeout/s/^/#/' /boot/loader/loader.conf
  sudo sed -i 's/$/ module_blacklist=iTCO_wdt quiet/' /etc/kernel/cmdline

  sudo sed -i '/^HOOKS=/ {s/base udev/systemd/; s/keymap consolefont/sd-vconsole/; s/ fsck//}' /etc/mkinitcpio.conf

  sudo cp ~/.local/wallpapers/bootctl/splash-memepad.bmp /usr/share/systemd/bootctl/
  sudo sed -i 's/splash-arch/splash-memepad/' /etc/mkinitcpio.d/linux.preset

  sudo mkinitcpio -P
}

configure_locale() {
  echo "#"
  echo "# Configuring locale..."
  echo "#"

  sudo sed -i '/^#en_US.UTF-8 UTF-8/s/^#//' /etc/locale.gen
  sudo locale-gen
}

configure_dns() {
  echo "#"
  echo "# Configuring DNS..."
  echo "#"

  sudo ln -sf ../run/systemd/resolve/stub-resolv.conf /etc/resolv.conf

  sudo mkdir -p /etc/systemd/resolved.conf.d/
  sudo tee /etc/systemd/resolved.conf.d/dns_over_tls.conf <<EOF
[Resolve]
DNS=1.1.1.1#one.one.one.one 1.0.0.1#one.one.one.one 2606:4700:4700::1111#one.one.one.one 2606:4700:4700::1001#one.one.one.one
DNSOverTLS=yes
Domains=~.
EOF

  sudo systemctl enable iwd.service
}

configure_home_dir() {
  echo "#"
  echo "# Configuring home directory..."
  echo "#"

  mkdir -p "${HOME}/Desktop/"
  mkdir -p "${HOME}/Documents/"
  mkdir -p "${HOME}/Downloads/"
  mkdir -p "${HOME}/Projects/"
  mkdir -p "${HOME}/Courses/"
  mkdir -p "${HOME}/Books/"
  mkdir -p "${HOME}/Music/"
  mkdir -p "${HOME}/Pictures/"
  mkdir -p "${HOME}/Videos/"
}

main() {
  echo "Prompting for sudo password to grant temporary password-less sudo..."
  sudo -v
  echo "$USER ALL=(ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/99-temp-postinstall >/dev/null
  trap 'sudo rm -f /etc/sudoers.d/99-temp-postinstall' EXIT

  configure_pacman
  install_packages

  restore_configs

  configure_silent_boot
  configure_locale
  configure_dns
  configure_home_dir

  echo '#'
  echo '# Post installation process complete!'
  echo '# You may reboot!'
  echo '#'
}

main "$@"
