#!/bin/bash
#
# Install software that I use on Arch Linux Hyprland
#
# - usage       : run this script after minimal install using ./archinstall.json

set -euo pipefail

github_url='https://github.com/moktavizen'

install_aur_helper() {
  sudo pacman -S --needed git base-devel --noconfirm
  git clone https://aur.archlinux.org/paru-bin.git
  cd paru-bin
  makepkg -si --noconfirm
  cd ..
  rm -rf paru-bin
}

install_packages() {
  local base=(
    'libva-intel-driver'
    'brightnessctl'
    'broadcom-bt-firmware'
    'iwd'
    'tlp'
    'zcfan'
    'greetd'
    'hyprland'
    'hyprpaper'
    'hyprlock'
    'hyprpicker'
    'polkit-kde-agent'
    'xdg-desktop-portal-hyprland'
    'xdg-desktop-portal-gtk'
    'qt5-wayland'
    'qt6-wayland'
    'noto-fonts'
    'noto-fonts-cjk'
    'noto-fonts-emoji'
    'noto-fonts-extra'
    'foot'
    'foot-terminfo'
    'zsh'
    'zsh-autosuggestions'
    'zsh-syntax-highlighting'
    'pacman-contrib'
    'stow'
    'grim'
    'slurp'
    'cliphist'
    'wlsunset'
    'pavucontrol'
    'bluetui'
    'impala'
    'waybar'
    'rofi-wayland'
    'rofi-emoji'
    'dunst'
  )

  local theme=(
    'qt6ct-kde'
    'breeze'
    'nwg-look'
    'adw-gtk-theme'
    'papirus-icon-theme'
    'inter-font'
    'adobe-source-serif-fonts'
    'ttf-jetbrains-mono-nerd'
  )

  local cli=(
    'man-db'
    'tmux'
    'fastfetch'
    'btop'
    'wget'
    'unzip'
    'fzf'
    'ripgrep'
    'eza'
    'bat'
    'fd'
    'hyperfine'
    'dust'
    'tokei'
    'oxipng'
    'imagemagick'
    'yt-dlp'
    'neovim'
    'tree-sitter-cli'
    'github-cli'
    'lazygit'
    'nodejs'
    'rustup'
  )

  local desktop_apps=(
    'gnome-disk-utility'
    'quickemu-git'
    'easyeffects'
    'obs-studio'
    'kdenlive'
    'inkscape'
    'gimp'
    'pinta'
    'pcmanfm-qt'
    'gwenview'
    'mpv'
    'zen-browser-bin'
  )

  local optional_deps=(
    'dosfstools'       # gnome-disk-utility
    'calf'             # easyeffects
    'libheif'          # gwenview
    'libavif'          # gwenview
    'kimageformats'    # gwenview
    'qt6-imageformats' # gwenview
  )

  local packages=(
    "${base[@]}"
    "${theme[@]}"
    "${cli[@]}"
    "${desktop_apps[@]}"
    "${optional_deps[@]}"
  )

  paru -Syyu --noconfirm

  echo "Installing ${#packages[@]} packages..."
  paru -S --needed --noconfirm "${packages[@]}"
}

configure_dotfiles() {
  git clone "${github_url}/dotfiles"
  cd dotfiles

  local dot_dirs=(
    'git'
    'paru'
    'hypr'
    'fontconfig'
    'menus'
    'wallpapers'
    'waybar'
    'rofi'
    'dunst'
    'easyeffects'
    'foot'
    'zsh'
    'fastfetch'
    'tmux'
    'bin'
    'nvim'
    'mpv'
  )

  stow --adopt "${dot_dirs[@]}"
  git restore .
}

configure_home() {
  mkdir -p "${HOME}/Desktop/"
  mkdir -p "${HOME}/Documents/"
  mkdir -p "${HOME}/Downloads/"
  mkdir -p "${HOME}/Projects/"
  mkdir -p "${HOME}/Courses/"

  sudo mkdir -p /media/Books/
  sudo mkdir -p /media/Music/
  sudo mkdir -p /media/Pictures/
  sudo mkdir -p /media/Videos/
  sudo chmod -R 777 /media
  ln -s /media/Books/ "${HOME}/Books"
  ln -s /media/Music "${HOME}/Music"
  ln -s /media/Pictures "${HOME}/Pictures"
  ln -s /media/Videos/ "${HOME}/Videos"
}

configure_extras() {
  sudo usermod -s "$(which zsh)" "$(whoami)"

  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "${HOME}/.config/powerlevel10k"

  mkdir -p "${HOME}/.local/share/color-schemes/"
  curl -fsSL "${github_url}/breeze-libadwaita/raw/main/kde/color-schemes/BreezeLibadwaitaDark.colors" \
    -o "${HOME}/.local/share/color-schemes/BreezeLibadwaitaDark.colors"

  sudo systemctl enable bluetooth.service
  sudo systemctl enable tlp.service
  sudo systemctl enable paccache.timer
}

configure_boot() {
  sudo sed -i '/^timeout/s/^/#/' /boot/loader/loader.conf
  sudo sed -i '/^options / {/ quiet/! s/$/ quiet/}' /boot/loader/entries/*_linux-lts.conf
}

configure_greeter() {
  sudo systemctl enable greetd.service

  sudo tee -a '/etc/greetd/config.toml' <<EOF

[initial_session]
command = "Hyprland > /dev/null"
user = "$(whoami)"
EOF
}

configure_pacman() {
  sudo sed -i '/^\[options\]/a\Color' /etc/pacman.conf
  sudo sed -i '/^\[options\]/a\ILoveCandy' /etc/pacman.conf

  sudo tee /etc/pacman.d/mirrorlist <<<'Server = http://sg.mirrors.cicku.me/archlinux/$repo/os/$arch'
}

configure_fan() {
  sudo tee /etc/modprobe.d/99-fancontrol.conf <<<'options thinkpad_acpi fan_control=1'
  sudo tee /etc/zcfan.conf <<EOF
max_temp 85
med_temp 70
low_temp 55
EOF

  sudo mkinitcpio -P
  sudo systemctl enable zcfan.service
}

configure_network() {
  sudo systemctl enable iwd.service

  sudo sed -i '/^\[Network\]/a\DNS=1.0.0.1' /etc/systemd/network/*.network
  sudo sed -i '/^\[Network\]/a\DNS=1.1.1.1' /etc/systemd/network/*.network
  sudo sed -i '/^\[Network\]/a\DNSOverTLS=yes' /etc/systemd/network/*.network
}

main() {
  install_aur_helper
  install_packages
  configure_dotfiles
  configure_home
  configure_extras
  configure_boot
  configure_greeter
  configure_pacman
  configure_fan
  # Must be last because this will cause no connection until reboot
  configure_network

  echo 'Post Installation process complete!'
  echo 'You may reboot!'
}

main "$@"
