#!/bin/bash
#
# postinstall
# Install software that I use on Arch Linux Hyprland
#
# Usage:
# run this script after minimal install using `archinstall --advanced`
# `curl -fsSL https://github.com/moktavizen/dotfiles/raw/main/postinstall | sh`

set -euo pipefail

github_url='https://github.com/moktavizen'

configure_pacman() {
  sudo sed -i '/^\[options\]/a\Color' /etc/pacman.conf
  sudo sed -i '/^\[options\]/a\ILoveCandy' /etc/pacman.conf

  sudo pacman -S --needed --noconfirm reflector
  sudo reflector --country Indonesia,Singapore --isos --delay 2 --sort rate --number 4 --save /etc/pacman.d/mirrorlist

  sudo pacman -S --needed --noconfirm git base-devel rustup
  rustup default stable
  git clone https://aur.archlinux.org/paru.git
  cd paru
  makepkg -si --noconfirm
  cd ..
  rm -rf paru
}

install_packages() {
  local base=(
    'libva-intel-driver-irql'
    'vulkan-intel'
    'mesa'
    'brightnessctl'
    'broadcom-bt-firmware'
    'noto-fonts'
    'noto-fonts-cjk'
    'noto-fonts-emoji'
    'noto-fonts-extra'
    'zsh'
    'zsh-autosuggestions'
    'zsh-syntax-highlighting'
    'zsh-theme-powerlevel10k-git'
    'man-db'
    'pacman-contrib'
  )

  local hyprland=(
    'hyprland'
    'hyprpaper'
    'hyprlock'
    'hyprpicker'
    'xdg-desktop-portal-hyprland'
    'xdg-desktop-portal-gtk'
    'polkit-kde-agent'
    'qt6-wayland'
    'greetd'
    'zcfan'
    'iwd'
    'tlp'
    'foot'
    'foot-terminfo'
    'waybar'
    'rofi'
    'dunst'
    'pavucontrol'
    'bluetui'
    'impala'
    'rofi-emoji'
    'cliphist'
    'wlsunset'
    'grim'
    'slurp'
  )

  local theme=(
    'qt6ct-kde'
    'breeze'
    'nwg-look'
    'adw-gtk-theme'
    'papirus-icon-theme'
    'inter-font'
    'ttf-jetbrains-mono-nerd'
  )

  local cli=(
    'stow'
    'tmux'
    'fastfetch'
    'btop'
    'eza'
    'fd'
    'bat'
    'dust'
    'fzf'
    'ffmpeg'
    'imagemagick'
    'yt-dlp'
    'neovim'
    'github-cli'
    'lazygit'
    'git-delta'
  )

  local gui_apps=(
    'easyeffects'
    'chromium'
    'dolphin'
    'ark'
    'gwenview'
    'haruna'
    'inkscape'
    'kdenlive'
    'obs-studio'
    'partitionmanager'
    'gnome-boxes'
    'qbittorrent'
    'jellyfin-server'
    'jellyfin-web'
  )

  local optional_deps=(
    'vulkan-mesa-layers' # vulkan-intel    : additional vulkan layers
    'calf'               # easyeffects     : mono speaker, since left broke
    'tree-sitter-cli'    # nvim            : tree-sitter auto_install
    'ripgrep'            # nvim            : snacks.picker
    'wget'               # nvim            : mason
    'unzip'              # nvim            : mason
    'npm'                # nvim            : mason
    '7zip'               # ark             : 7zip format
    'unrar'              # ark             : RAR format
    'kimageformats'      # gwenview        : support additional formats
    'qt6-imageformats'   # gwenview        : support additional formats
    'libheif'            # gwenview        : HEIF format
    'libavif'            # gwenview        : AVIF format
    'dosfstools'         # partitionmanager: FAT format
  )

  local packages=(
    "${base[@]}"
    "${hyprland[@]}"
    "${theme[@]}"
    "${cli[@]}"
    "${gui_apps[@]}"
    "${optional_deps[@]}"
  )

  paru -Syyu --noconfirm

  echo "Installing ${#packages[@]} packages..."
  paru -S --needed --noconfirm "${packages[@]}"
}

configure_bootloader() {
  sudo sed -i '/^timeout/s/^/#/' /boot/loader/loader.conf
  sudo sed -i '/^options / {/ quiet/! s/$/ quiet/}' /boot/loader/entries/*_linux-lts.conf
}

configure_display_manager() {
  sudo systemctl enable greetd.service

  sudo tee -a '/etc/greetd/config.toml' <<EOF

[initial_session]
command = "Hyprland > /dev/null"
user = "$(whoami)"
EOF
}

configure_locale() {
  sudo sed -i '/^#en_US.UTF-8 UTF-8/s/^#//' /etc/locale.gen
  sudo locale-gen
}

configure_network() {
  sudo ln -sf ../run/systemd/resolve/stub-resolv.conf /etc/resolv.conf

  sudo mkdir -p /etc/systemd/resolved.conf.d/
  sudo tee /etc/systemd/resolved.conf.d/dns_over_tls.conf <<EOF
[Resolve]
DNS=1.1.1.1#one.one.one.one 1.0.0.1#one.one.one.one 2606:4700:4700::1111#one.one.one.one 2606:4700:4700::1001#one.one.one.one
DNSOverTLS=yes
Domains=~.
EOF

  sudo systemctl enable iwd.service
}

configure_fan_control() {
  sudo tee /etc/modprobe.d/99-fancontrol.conf <<<'options thinkpad_acpi fan_control=1'
  sudo tee /etc/zcfan.conf <<EOF
max_temp 85
med_temp 70
low_temp 55
EOF

  sudo mkinitcpio -P
  sudo systemctl enable zcfan.service
}

enable_systemd_units() {
  sudo systemctl enable bluetooth.service
  sudo systemctl enable tlp.service
  sudo systemctl enable paccache.timer
}

configure_user_env() {
  mkdir -p "${HOME}/Desktop/"
  mkdir -p "${HOME}/Documents/"
  mkdir -p "${HOME}/Downloads/"
  mkdir -p "${HOME}/Projects/"
  mkdir -p "${HOME}/Courses/"

  sudo mkdir -p /media/Books/
  sudo mkdir -p /media/Music/
  sudo mkdir -p /media/Pictures/
  sudo mkdir -p /media/Videos/
  sudo chmod -R 777 /media
  ln -s /media/Books/ "${HOME}/Books"
  ln -s /media/Music "${HOME}/Music"
  ln -s /media/Pictures "${HOME}/Pictures"
  ln -s /media/Videos/ "${HOME}/Videos"

  git clone "${github_url}/dotfiles"
  cd dotfiles
  stow */

  sudo usermod -s "$(which zsh)" "$(whoami)"

  nwg-look -a -x
}

main() {
  configure_pacman
  install_packages
  configure_bootloader
  configure_display_manager
  configure_locale
  configure_network
  configure_fan_control
  enable_systemd_units
  configure_user_env

  echo 'Post installation process complete!'
  echo 'You may reboot!'
}

main "$@"
