[main]
shell=/usr/bin/env fish
font=monospace:pixelsize=14
font-bold=monospace:pixelsize=14
font-italic=monospace:pixelsize=14
font-bold-italic=monospace:pixelsize=14
pad=12x10 center-when-maximized-and-fullscreen
# include=/usr/share/foot/themes/xterm

[key-bindings]
spawn-terminal=Mod4+Return

[colors-dark]
regular0=1e1e1e
regular1=ffa198
regular2=7ee787
regular3=e3b341
regular4=79c0ff
regular5=d2a8ff
regular6=a5d6ff
regular7=e9e9e9
bright0=9d9d9d
bright1=ffa198
bright2=7ee787
bright3=e3b341
bright4=79c0ff
bright5=d2a8ff
bright6=a5d6ff
bright7=e9e9e9
foreground=e9e9e9
background=1e1e1e
cursor=1e1e1e 79c0ff
selection-background=555555
